#!/usr/bin/env bash
readarray -d '' RM_HISTORY < <(git log -z --diff-filter=D --format=%H)
for COMMIT in "${RM_HISTORY[@]}"; do
  readarray -d '' FILES < <(git log -1 -z --name-only --diff-filter=D --format= "${COMMIT}")
  for FILE in "${FILES[@]}"; do
    if [ -e "${FILE}" ]; then
      echo "${FILE} exists"
    else
      echo "restore ${FILE}"
      git restore --source="${COMMIT}"~ "${FILE}"
    fi
  done
done
